import {TranslatedText} from '../stores/LanguageStore';

export const english: TranslatedText = {
  lang: 'Language',
  today: 'Today',
  locationTabTitle: 'Location',
  favouritesTabTitle: 'Favourites',
  temperature: 'Temperature',
  minTemperature: 'Min temperature',
  maxTemperature: 'Max temperature',
  mainWeatherCondition: 'Weather Condition',
  sunset: 'Sunset',
  sunrise: 'Sunrise',
  wind: 'Wind',
  humidity: 'Humidity',
  clouds: 'Clouds',
  visibility: 'Visibility',
  searchCity: 'Search City',
  favouriteCities: 'Favourite Cities',
  cancel: 'Cancel',
  noDataFound: 'No Data Found!',
  forecast: 'Forecast',
  monday: 'Monday',
  tuesday: 'Tuesday',
  wednesday: 'Wednesday',
  thursday: 'Thursday',
  friday: 'Friday',
  saturday: 'Saturday',
  sunday: 'Sunday',
};
